spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: mariadb
    url: jdbc:mariadb://localhost:3303/test
    username: root
    password: root
    driverClassName: org.mariadb.jdbc.Driver
